In [1]:
import tensorflow_probability as tfp
import tensorflow as tf
import matplotlib.pyplot as plt

In [3]:
num_trial = [i for i in range(0, 200, 10)]
num_trial = tf.constant(num_trial)
num_trial

<tf.Tensor: shape=(20,), dtype=int32, numpy=
array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190])>

In [10]:
rv_coin_flip_prior = tfp.distributions.Bernoulli(probs=0.5, dtype=tf.int32)
data = rv_coin_flip_prior.sample(num_trial[-1])
data = tf.pad(data,tf.constant([[1, 0,]]),"CONSTANT")
cumulative_headcounts = tf.gather(tf.cumsum(data), num_trial)
cumulative_headcounts

<tf.Tensor: shape=(20,), dtype=int32, numpy=
array([  0,   6,  14,  20,  22,  28,  34,  40,  45,  50,  58,  64,  70,
        74,  80,  85,  89,  95, 101, 106])>